### ISSUE TITLE
Improving Translation Accuracy

### ISSUE THREAD

**Issue by huncut2016** [3b1b/captions#10]
# Issue
I'd like to emphasize that making minor adjustments is easier to rectify than translating the entire text from scratch. To illustrate, Hungarian translations often contain inaccuracies and can sometimes be misleading.

# Solution
Based on my research, [DeepL](https://www.deepl.com/) appears to be the most reliable tool for English-Hungarian translation. Consequently, I encourage other native speakers to suggest alternative translation services they find satisfactory. Subsequently, these can be integrated into the existing pipeline.

**Comment by YoungPetya** [comment]
Agreed, I have friends and relatives who work with languages in Budapest and do professional translations; DeepL is the most reliable tool for English to Hungarian translations. Do we know what tool was used for the current versions?

**Comment by 3b1b** [comment]
This is good to know. For this initial pass, I used Google's translation API, but I'll look into DeepL and maybe do another pass over everything.

**Comment by 3b1b** [comment]
I ran DeepL on a few transcripts just to compare. Does [this Hungarian translation](https://github.com/3b1b/captions/pull/90/files#diff-0ddcf01ae69572f8c89da2fe56bf02ba3d665953df2b022153bd62d915d30d10) look better to you than the original Google one? If so, how significant is it?

**Comment by huncut2016** [comment]
Yes, it's incomparable, a huge difference. I realized that in most of the cases, the inaccuracy comes from the fact that the translator doesn't have any context. So my idea is that we can feed the whole text into the translator and because the '.', '?', and '!' characters stay in the original position, preserving the sentence boundaries, reconstructing the chunks is pretty easy.
Still, if it's too big at once, we could implement some rolling window technique.

**Comment by 3b1b** [comment]
To be clear, you're saying the sentence-by-sentence translations from DeepL are good, but that you'd suggest they could be even better with context, is that right?

**Comment by huncut2016** [comment]
Yepp
