### ISSUE TITLE
Dutch only has community.srt files, and can't upload .json files

### ISSUE THREAD

**Issue by CactusBrothers** [3b1b/captions#108]
On most videos there is no Dutch present, but on some there is a "community.srt" file. My first question is what this file is supposed to be, as it doesn't seem to be human translated (if it was, no offense, but they would suck at Dutch).

For the video dp3t I have converted the .srt file to a .json file in the correct format and revised it to be proper Dutch, but without the "input" field as there doesn't seem to be an English transcript/subtitle file with corresponding times. I tried uploading the files to the repo, but I don't have permission (for a good reason!) to upload files so I uploaded them on a fork: https://github.com/CactusBrothers/captions-dutch/commit/c40c03feb4368f5b320c29ce7886e4b2817468b2 . 

So the question is:
What is the deal with the "community.srt" files?

Love this initiative and I will definitely be checking the Dutch translations!

**Comment by 3b1b** [comment]
In the old days, YouTube allowed for community contributions to subtitles. In forming this repo, I first downloaded all the existing captions on videos, and gave them the suffix "community.srt".  It's a shame the Dutch ones are not good.

If you have a request for new Dutch translations, let me know a few videos you would want and I can run the script to get the machine-generated sentence_translation.json files for those, which by the sounds of it would be an easier starting place than the previous community contributions.
