### ISSUE TITLE
Suggestion: Claiming System?

### ISSUE THREAD

**Issue by tempodat** [3b1b/captions#11]
It could be really disheartening to take on a translation project that's larger than a few scripts, knowing that by the time you're done half of them could have already been fixed. Could there be a way to organize work between us, or even a way to know if someone's already done work to a specific video/file?

(a discord server to coordinate in would go a long way towards solving this imo)

**Comment by 3b1b** [comment]
That's a good suggestion. I'll throw something together for that and get back shortly

**Comment by marcelolynch** [comment]
It would also be useful to be able to add links to the related pull requests so other people can review (and, say, "claim" that it's being reviewed)

**Comment by omertuc** [comment]
Until a better system exists, I offer people create draft pull requests that mention what they're working on. Make sure to include the language in the title so people can discover it

**Comment by 3b1b** [comment]
Alright, I just made a Discord server and will figure out the best way to manage it: https://discord.gg/MSKzxDgTGE

Thanks for bearing with me here.
