### ISSUE TITLE
[SUGGESTION] Add labels for languages

### ISSUE THREAD

**Issue by RisingSunLight42** [3b1b/captions#110]
Everything is in the title. I think it would be better to add a label for each language to help the filtering on issues and PR. Since the formatting on the title is good, but not as readable and filterable as labels.

**Comment by Yag000** [comment]
Already addressed in issue #43. Labels have been automated and will now be applied to new PRs as they are opened. The current implementation triggers the action to update labels upon PR creation only. If @3b1b deems it necessary, I can submit a pull request (PR) to retroactively update previous labels. However, this process would require an additional PR to remove the temporary code. Currently, the action runs each time a new PR is created, assigning labels accordingly. Implementing this on already opened PRs involves a temporary commit. Once completed, this commit becomes unnecessary, and we should consider removing it. (Doing it manually is not an option either)

**Comment by RisingSunLight42** [comment]
Oh okay, nvm then. I've saw nothing 'bout that while checking the repo. Sorry for the inconvenience 😅

**Comment by Yag000** [comment]
No problem! If there's only been one new PR since the merge, it's normal that the change is not immediately noticeable :)
