### ISSUE TITLE
Merging gidelines

### ISSUE THREAD

**Issue by Yag000** [3b1b/captions#111]
Following a discussion on the Spanish channel on Discord, I would like to inquire about guidelines regarding when a translation PR is ready to merge.

The Spanish community has a good number of active members who diligently review each other's PRs, which is excellent for catching typos and mistakes. I have observed similar practices in other languages, particularly German. I am interested in knowing if there is a way to "institutionalize" reviews, especially for "larger" communities. If there are only one or two contributors for a language this does not make much sense.

In particular, for the Spanish community, we face challenges due to the diverse ways Spanish is spoken across various countries, with sometimes radical differences. We would appreciate having different perspectives before merging to address these variations.

**Comment by jebalke** [comment]
Absolutely! Working on possible solutions for this now as well as tracking the ongoing/recurring issues within a language, so we can know what changes should be made longer-term - Jordan
