### ISSUE TITLE
Suggestion: Bulgarian language

### ISSUE THREAD

**Issue by SimeonTheCoder** [3b1b/captions#113]
I know a lot of people in my country watch your videos and respect them. There's a bit of a math problem since a lot of people aren't that interested in math and the old teachers that don't speak English don't help that. I would love to help out with a possible Bulgarian translation that could reach more people and ignite their passion for math! I know damn well it did for me!

**Comment by ChavdarNenov** [comment]
i would also suggest that the "Essence of" series gets translations in Bulgarian. other videos could be translated afterwards.

**Comment by mxhellish** [comment]
+1

**Comment by 3b1b** [comment]
Sure thing, I just added some for the Calculus series

**Comment by ChavdarNenov** [comment]
Can we have a discord chanel where we can discuss the work flow and future video translations? Thanks in advance.
