### ISSUE TITLE
Suggestion: Adding popular IDE folders to .gitignore

### ISSUE THREAD

**Issue by mxhellish** [3b1b/captions#120]
It would be nice if the folders of popular IDEs are added to the .gitignore

**Comment by 3b1b** [comment]
Would you like to make a PR?

**Comment by mxhellish** [comment]
I made a pull request with IDEs from the top of my head

**Comment by 3b1b** [comment]
Alright, just let me know when you feel happy with it, and I'll merge.

**Comment by mxhellish** [comment]
The people on discord had no concerns. I guess you can approve the PR.
