### ISSUE TITLE
Suggestion: Dutch translations of crypto videos

### ISSUE THREAD

**Issue by bvdeijzen** [3b1b/captions#126]
Hi, I would like to help translating some videos into Dutch, specifically the videos on cryptocurrencies:

- bitcoin
- 256-bit-security

I have already translated the 256-bit-security video without the machine-generated translations. However, it would save a lot of time if I could use the rough translations. Would you like to add the files for these two videos?

Thanks in advance, and thanks for your awesome videos.

**Comment by 3b1b** [comment]
Sure thing, I just added them.
