### ISSUE TITLE
The Czech translation of Essence of linear algebra series.

### ISSUE THREAD

**Issue by Chnapak** [3b1b/captions#142]
Hey, I gained a new translator to our Czech translation team and he is interested in the translation of the Essence of linear algebra series into Czech because of big national exam comming up in the Czech republic. After reviewing said video files I saw community files, can we request an AI translation and translate the sentence_translation.json files or should we only change the community files? Thanks :)

**Comment by 3b1b** [comment]
Sure thing, I just pushed some translations of that series into Czech
