### ISSUE TITLE
Misc app UI enhancements

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/captions#336]
- Add "upload zip" option, to resume work from a previously exported zip.
- Add "see raw" button next to flag button in each row that links to raw json files on github for inspection? `#:~:text=`
- More descriptive body text for linked issues (e.g. flag button, .json missing link, etc.). Maybe line/index number of entry? Maybe also include input English text?

**Comment by FaboBence** [comment]
I would greatly appreciate the upload ZIP option. I don't like submitting half-done files, but if I translate in multiple session, sometimes the page reloads itself and all my changes are stuck in the saved ZIP file.
