### ISSUE TITLE
Suggestion: Language labels 

### ISSUE THREAD

**Issue by Yag000** [3b1b/captions#43]
We should make it easier to know the language of each pull request for smoother reviews. 

While some mention it in the title, enforcing a format can be tricky. A simple solution could be using labels, automatically set by the [labeler action](https://github.com/actions/labeler). For example, a PR changing `https://github.com/3b1b/captions/blob/main/2023/ego-and-math/spanish/sentence_translations.json` could be labeled as 'Spanish' since it's in the 'spanish' directory, and the same for the other languages.

If you agree, I can submit a PR for this.

**Comment by 3b1b** [comment]
That sounds like an outstanding idea, please do submit the PR

**Comment by Yag000** [comment]
@3b1b  I've made the PR
