### ISSUE TITLE
differential-equations (DE1) - translation sync is lost at 1163.89

### ISSUE THREAD

**Issue by davidBar-On** [3b1b/captions#437]
**Original**
In his book Chaos, the author James Glick describes phase space as, "O

**Translation (French)**:
Dans son livre Chaos, l'auteur James Glick décrit l'espace des phases comme suit : &quot;.

**Time**:
1163.89 - 1186.89

**Line**
Entry # 139
Line # ~1115

**Describe the issue**
This issue exist at least in the French and Hebrew translations, but I assume it is common to most of the translations.  About 23 seconds are allocated to this part of the translation, although it takes only few seconds (is it because of the "\&quot;"?).  From this point on, the translation and video are not synchronized.

Note that the English transcript does not have this issue, so it maybe that the English transcript was fixed without re-running the auto translations.

**Comment by 3b1b** [comment]
I'm not sure what happened there. In converting to the new non-GitHub system, criblate, I think most of those syncing issues were fixed, though there's a little funkiness with sporadically added blank captions: https://criblate.com/video/p_di4Zn4wz4/iw/transcript/667c510994374f2cd14a1363
