### ISSUE TITLE
Suggestion: Consistent formality in German translations

### ISSUE THREAD

**Issue by ectem7** [3b1b/captions#54]
## Consistent formality in German translations
When translating from **English** to **German**, a certain degree of freedom is left to the translator. This freedom boils down to the **formality** of the text. As other contributors have pointed out, the pronoun you has several translations at least that each come with a different verb conjugation, most notably:
- **Du** (Singular, informal)
- **Sie** (Singular, very formal)[^1]

Grammatical gender, too, plays a role in this. To avoid any inconsistencies between translations, I'd like to suggest @3b1b let us know what level of formality he finds appropriate for his target audience in advance. 
[^1]: See [this article](https://grammar.collinsdictionary.com/de/deutsch-grammatik-lernen/how-do-you-know-when-to-use-du-ihr-or-sie-in-german) for more information on German pronouns.

**Comment by DLLuatic** [comment]
Actually, you might want to consider translating "you" as in "you guys" (2nd person plural, also "Ihr"), since that makes way more sense sometimes. Case and point - "I would like to see how you guys would solve this in the comments" -> "Es wäre interessant zu sehen, wie ihr das in den Kommentaren angehen würdet" vs. "Es wäre interessant zu sehen, wie du das in den Kommentaren angehen würdest". First one sounds better if you consider that most viewers watch this on Youtube, does it not? Just my two cents.

**Comment by lole370** [comment]
I totally agree that this should be consistent throughout the translations. Another option would be to not address the viewer directly but by addressing them by using the plural form **Wir**(we).

An example from [the mandelbrot short](https://github.com/3b1b/captions/blob/main/2024/shorts/mandelbrot/german/sentence_translations.json):

input: `You start with some complex number, c, and`...
Current translation: `Sie beginnen mit einer komplexen Zahl, c, und`...

The current translatio is, as @ectem7 pointed out, very formal and probably not ideal here.

Translation with **Du**: `Du beginnst mit einer komplexen Zahl, c, und`...
This is much more informal and probably the way a teacher would explain it to a single student if they had a question about the topic.

Possible translation with **Wir**: `Wir beginnen mit einer komplexen Zahl, c, und`...
This, to me, sounds much more like a sentence a techer would say to a class. It would translate to `We start with some complex number, c, and`...

Of course the way thats used in the end can differ for different video formats. Maybe for shorts the viewer should be addressed more directly but i still think having a clear decision here would be important.

**Comment by 3b1b** [comment]
My goal is typically for it to feel like one friend explaining something to another. From what I'm reading, that suggests "Du" might be appropriate, but not speaking German I of course can't tell whether that ends up sounding strange in other ways for certain parts of certain videos.
