### ISSUE TITLE
Suggestion: Using a package that produces better timestamps than Whisper

### ISSUE THREAD

**Issue by LuisAVasquez** [3b1b/captions#60]
### Context

Whisper is great for transcriptions, however, its timestamps for subtitles are pretty clunky. Why? Because Whisper aligns at the _phrase_ level

### Solution

I have been working on a Python package for video transcription that uses Whisper and WhisperX, which is an extension of Whisper that aligns _at the word_ level. You can try it out [on this Colab notebook](https://colab.research.google.com/drive/1KdW7tsBGyFSpxBZ4c_rW9-jeUaVVtnJ7?usp=drive_link&authuser=1#scrollTo=pBdZtgnxgs4J). Here is the result of transcribing the [But what is a Neural Network?](https://www.youtube.com/watch?v=aircAruvnKk&t=51s) video: as a [SRT subtitles file](https://drive.google.com/file/d/17rlqsNDwXSWo-Z8bdNLjNtlKZMGxbwam/view?usp=drive_link) and as [plaintext file](https://drive.google.com/file/d/16VA17BfVWy3pfZ2azhR4xT52kS1uidby/view?usp=drive_link)

### Proposal

Using this package would save the community a lot of manual effort in re-aligning the subtitles, as its alignment quality is far better than that of the original Whisper.

#### PD

This is not shameless self-promotion, I am genuinely interested in helping :)

**Comment by 3b1b** [comment]
I thought Whisper's word alignment was pretty good, I've been using it to produce files like [this one](https://github.com/3b1b/captions/blob/main/2017/neural-networks/english/word_timings.json). There's a specific option you have to set to True.

>     word_timestamps: bool
>         Extract word-level timestamps using the cross-attention pattern and dynamic time warping,
>         and include the timestamps for each word in each segment.

Can you provide an example where it seems to fail?

**Comment by LuisAVasquez** [comment]
I just re-checked [WhisperX](https://github.com/m-bain/whisperX)'s documentation, and their alignment is at the _phoneme level_, very fine grained

**Comment by 3b1b** [comment]
Good to know. To generate subtitles and dubbing, the word level seems accurate enough for these purposes. I'll note the suggestion, but close the issue for now.
