### ISSUE TITLE
Suggestion: Dutch

### ISSUE THREAD

**Issue by LFWarsen** [3b1b/captions#96]
I would love to help bring 3b1b to Dutch!

As a start I would like to work on the "Essence of Calculus" course. To this end I would like to request the rough generated translations of the first 4 videos of [The Essence of Calculus](https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr).

A Dutch channel on the Discord server would also be appreciated, in case anyone wants to help.

Thank you for the amazing content :)

**Comment by 3b1b** [comment]
Thanks for the suggestion, I just added the first four to calculus.
