### ISSUE TITLE
What about the words on the screen ?

### ISSUE THREAD

**Issue by Jonhfing** [3b1b/captions#99]
Would there be any easy way to translate the words and variables that appear on the screen ? I doubt it but I'm no expert. If not doable, is it better to translate the corresponding words/variables in the text, or leave them as is ? I think this could be awkward either way. I got this issue translating V - E + R = 2 from the Moser circle problem, which would translate as N - A + R = 2. While it's awkward hearing and seeing two different things, I think it's worse to not understand where the letters are coming from.

**Comment by 3b1b** [comment]
I agree a fully localized video would translate the words on the screen as well. For the time being, the scope of the project I have in mind is to get a good system in place for putting up dubbing as alternate audio tracks on existing videos.

The policy I've always had is that if people want to create a fully localized video, with translated text on the screen and dubbing, I'll give them permission to an official translation channel where they can upload it, and share the revenue. Some people have, and I'm deeply grateful when they do, but the process reliably takes much, much longer than people anticipate.

If this auto-dubbing project seems like it'll work, and if we put together a good system for coordinating contributions and automatically transforming the results into audio and uploading them, then we can perhaps widen the scope to creating fully localized videos. One step at a time, though.

**Comment by 3b1b** [comment]
It would have to be a very manual process, there's no way around that. The best way would involve adding the new translated text on top of the existing video, trying to re-run and re-edit the original animations would be a nightmare.
